Fix HTTP server support of UNIX filesystem sockets
https://github.com/twisted/twisted/pull/12312 changed HTTPChannel to
call setTcpNoDelay() on any transport implementing ITCPTransport.
Transports via UNIX socket also implement this interface. As a result,
setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, ...) was called on
UNIX socket, which fails via:

builtins.OSError: [Errno 95] Operation not supported

To avoid the problem, unix.Server and unix.Client now implement
setTcpNoDelay() and friends that do nothing.